name: Slack Notification
run-name: Pushing notification on Slack channel

on: [push]

jobs:
  Notify-Slack-Channel:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate build start time
        id: build_start_time
        run: echo "BUILD_START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Calculate build duration
        id: calculate_duration
        run: |
          end_time=$(date +%s)
          duration=$((end_time - $BUILD_START_TIME))
          echo "duration=$duration" >> $GITHUB_ENV
          echo "::set-output name=duration::$duration"

      - name: Get short commit hash
        id: short_commit
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
        payload: |
            {
            "blocks": [
                {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*:white_check_mark: Succeeded GitHub Actions*"
                }
                },
                {
                "type": "section",
                "fields": [
                    {
                    "type": "mrkdwn",
                    "text": "*Repo*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Commit*\n<${{ github.event.head_commit.url }}|${{ env.SHORT_SHA }}>"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Author*\n${{ github.event.head_commit.author.name }}"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Job*\n`${{ github.job }}`"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Event Name*\n`${{ github.event_name }}`"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Workflow*\n`${{ github.workflow }}`"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Build Logs*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Took*\n`${{ steps.calculate_duration.outputs.duration }} sec`"
                    },
                    {
                    "type": "mrkdwn",
                    "text": "*Message*\n${{ github.event.head_commit.message }}"
                    }
                ]
                }
            ]
            }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
